In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.randint(25, size=(3,4,5))
a

tensor([[[ 0,  8,  9, 21,  7],
         [11, 22,  6, 13, 19],
         [ 3,  3, 16, 21, 18],
         [22, 19,  9, 18, 17]],

        [[ 9,  8,  8, 20,  1],
         [20, 14, 10,  5,  9],
         [12,  7, 22,  8, 19],
         [ 3, 22,  9, 14, 12]],

        [[ 6, 11,  5, 15, 13],
         [11, 11,  1, 11, 20],
         [ 1,  2, 20, 11, 12],
         [18, 20,  2, 16,  4]]])

In [3]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
a = a.reshape(6,10)
a

tensor([[ 0,  8,  9, 21,  7, 11, 22,  6, 13, 19],
        [ 3,  3, 16, 21, 18, 22, 19,  9, 18, 17],
        [ 9,  8,  8, 20,  1, 20, 14, 10,  5,  9],
        [12,  7, 22,  8, 19,  3, 22,  9, 14, 12],
        [ 6, 11,  5, 15, 13, 11, 11,  1, 11, 20],
        [ 1,  2, 20, 11, 12, 18, 20,  2, 16,  4]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(50, size=(10,))
b

tensor([ 5, 26,  5, 40, 48, 23, 37,  2, 25,  4])

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

c = a * b
c

tensor([[  0, 208,  45, 840, 336, 253, 814,  12, 325,  76],
        [ 15,  78,  80, 840, 864, 506, 703,  18, 450,  68],
        [ 45, 208,  40, 800,  48, 460, 518,  20, 125,  36],
        [ 60, 182, 110, 320, 912,  69, 814,  18, 350,  48],
        [ 30, 286,  25, 600, 624, 253, 407,   2, 275,  80],
        [  5,  52, 100, 440, 576, 414, 740,   4, 400,  16]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

d = c.matmul(c.T)
d

tensor([[1701935, 1867622, 1314825, 1415705, 1265063, 1416818],
        [1867622, 2422498, 1389543, 1848908, 1611259, 1790259],
        [1314825, 1389543, 1186438,  843962,  936291, 1019105],
        [1415705, 1848908,  843962, 1775453, 1266571, 1458642],
        [1265063, 1611259,  936291, 1266571, 1144384, 1158156],
        [1416818, 1790259, 1019105, 1458642, 1158156, 1417373]])

In [12]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([0.5], requires_grad=True)
z = torch.tensor([2.], requires_grad=True)

t =  (x**3 + z - y) / 75
t

tensor([0.0333], grad_fn=<DivBackward0>)

In [10]:
# 8. Создайте единичный тензор размера 5x6

ones = torch.ones((5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [14]:
# 9. Переведите его в формат numpy

np_ones = ones.numpy()
np_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)